server:
  port: 8881
spring:
  flyway:
    locations: classpath:/db/testdata
    datasource:
      drier-class-name: org.h2.Drier
      url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
        username: sa
        password: 1
    jpa:
      show-sql: true
        properties:
          hibernate:
            dialect: org.hibernate.dialect.H2Dialect
